version: 0.2

env:
  parameter-store:
    REACT_APP_ENV: "APP_DEV_ENV"

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Dev Build started on `date`
      - npm run dist:dev
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  base-directory: build
